before_install:
  - git clone https://github.com/confluentinc/common.git
  - cd common
  - git checkout v4.1.0-rc3
  - mv pom.xml pom.xml.bak && sed  '58s/.*/        <kafka.version>1.1.0<\/kafka.version>/' pom.xml.bak > pom.xml
  - mvn -B clean install -Dmaven.test.skip=true
  - cd ..
  - git clone https://github.com/confluentinc/support-metrics-common.git
  - cd support-metrics-common
  - git checkout v4.1.0-rc3
  - mvn -B clean install -Dmaven.test.skip=true
  - cd ..
  - git clone https://github.com/confluentinc/rest-utils.git
  - cd rest-utils
  - git checkout v4.1.0-rc3
  - mvn -B clean install -Dmaven.test.skip=true
  - cd ..
  - git clone https://github.com/confluentinc/schema-registry.git
  - cd schema-registry
  - git checkout v4.1.0-rc3
  - mvn -B clean install -Dmaven.test.skip=true
  - cd ..
  - git clone https://github.com/confluentinc/ksql.git
  - cd ksql
  - git checkout v4.1.0-rc3
  - ex -sc '55d7|x' ksql-cli/pom.xml && ex -sc '37d7|x' ksql-engine/pom.xml && ex -sc '25d7|x' ksql-parser/pom.xml && ex -sc '84d7|x' ksql-rest-app/pom.xml && ex -sc '37d7|x' ksql-tools/pom.xml
  - mvn -B clean install -Dmaven.test.skip=true
  - cd ..
script:
  - sbt clean coverage test it:test coverageReport && sbt coverageAggregate
after_success:
  - sbt coveralls