before_install:
  - git clone https://github.com/confluentinc/ksql.git && cd ksql
  && git checkout 0.1.x
  && mvn -pl '!ksql-cli' clean install -Dmaven.test.skip=true
script:
  - sbt clean coverage test coverageReport && sbt coverageAggregate
after_success:
  - sbt coveralls